### ISSUE TITLE
Crear Issues para cada cosa que hagas y enlazarlo con clockify

### ISSUE THREAD

**Issue by spdvi** [Diego-bih/ToolsManager#2]
HOla, tal como dijimos, tienes que crear un Issue cada vez que vayas a hacer una funcionalidad del proyecto y enlazar ese Issue con clockify. HAs de instalar el pluguin de clockify para tu navegador y lo veras en los issues:
![image](https://user-images.githubusercontent.com/62358226/160787927-7aaa4cd9-dff4-4c56-9c46-c352ae092252.png)
Además, en los commits que hagas también has de hacer referencia al issue en el que estas trabajando en ese commit. Simplemente añade la linea #issuenumber al principio del commit.

**Comment by Diego-bih** [comment]
De acuerdo
