### ISSUE TITLE
Rererencia a USERSPATH erronea

### ISSUE THREAD

**Issue by spdvi** [Diego-bih/ToolsManager#3]
En tu projecto está USERSPATH como "C:\\Users\\Diego Ramirez\\AppData\\Local\\ToolsManager\\data\\Usuaris.csv"
Cuando el proyecto o aplicación se lleva a otro equipo, ese path no existe.
Has de usar System.getProperty("user.home") mas la ruta relativa en AppData.
Revisa el ejercicio OpusList si tienes dudas.

**Comment by Diego-bih** [comment]
Si, ya esta solucionado.
![image](https://user-images.githubusercontent.com/77398946/160883151-34daa0a2-bb0b-4fd2-a40d-ae17b0161dd2.png)
