### ISSUE TITLE
Nombres de los componentes visuales

### ISSUE THREAD

**Issue by spdvi** [Diego-bih/ToolsManager#5]
Los componente visuales han de tener un nombre descriptivo tal como vimos en clase.
P.ej: btnLogin, btnGenerateData, txtEmail, etc.
Revisa los prefijos que se usan para cada componente.
Igualmente hay que cuidar mucho los nombers de las clases, las variables, los métodos, etc.

**Comment by Diego-bih** [comment]
Hecho.
