### ISSUE TITLE
Imagen usuario

### ISSUE THREAD

**Issue by spdvi** [Diego-bih/ToolsManager#6]
Al registrar a un usuario debes permitirle elegir una imagen de perfil, aunque sea del disco de la máquina donde se encuentra. Si no elige ninguna puedes asignarle una por defecto.

**Comment by Diego-bih** [comment]
De acuerdo.
![image](https://user-images.githubusercontent.com/77398946/161582674-c273b64c-3a4f-443e-b0ae-1c0e88179c86.png)
